# values.yaml

# --- Persistence ---
storage:
  size: 2Gi

# --- Service ---
service:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 50051
      targetPort: 50051

# --- Resources ---
resources:
  limits:
    cpu: "1"
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# --- Auth (keep anon for local dev) ---
authentication:
  anonymous_access:
    enabled: true

# --- Image ---
image:
  tag: "1.31.5"
  pullPolicy: IfNotPresent

# --- Important: enable modules via env ---
extraEnv:
  - name: ENABLE_MODULES
    value: "generative-openai"
  - name: DEFAULT_VECTORIZER_MODULE
    value: "none"           # BYOV: do NOT enable text2vec-*
  # Option A (server knows the key; easiest to verify)
  - name: OPENAI_APIKEY
    valueFrom:
      secretKeyRef:
        name: openai-api
        key: apiKey
