apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-local-plugins-folder
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/brayantorres/Documents/tfm/dags" 