apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-local-plugins-folder
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi 