apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-local-dags-folder
  namespace: airflow
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi 